job:
  permissions:
    id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
    contents: read
  steps:
    - name: Deploy to Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: ytdl # the name of the project on Deno Deploy
        entrypoint: index.ts # the entrypoint to deploy
